### ISSUE TITLE
Build not working on MacOS Ventura 13.4.1.c

### ISSUE THREAD

**Issue by Markar** [fluffos/fluffos#995]
This seems to be an issue with not having libicu-dev, which doesn't seem to come with icu4c. 

Steps:
$ git clone https://github.com/fluffos/fluffos.git
$ cd fluffos
$ git checkout master #(or an release tag)
$ brew install cmake pkg-config mysql pcre libgcrypt libevent openssl jemalloc icu4c
$ mkdir build && cd build
$ OPENSSL_ROOT_DIR="/usr/local/opt/openssl" ICU_ROOT="/usr/local/opt/icu4c" cmake ..
$ make install

make install fails with `strutils.h:6:10: fatal error: 'unicode/brkiter.h' file not found`

**Comment by michaelprograms** [comment]
The build instructions from https://www.fluffos.info/build.html might be out of date, the OSX build workflow has some different dependencies listed.

```bash
brew install cmake pkg-config pcre libgcrypt openssl jemalloc icu4c mysql-client sqlite3 googletest
```
https://github.com/fluffos/fluffos/blob/master/.github/workflows/ci-osx.yml

**Comment by michaelprograms** [comment]
Updating for documentation purposes. Running into this issue on a Mac running OS X 14 (Sonoma), adding this for anyone that runs into it in the future.

I followed the steps from:
* `brew icu4c info`
* `brew link icu4c --force`
* used `ICU_ROOT="/opt/homebrew/opt/icu4c"`
